services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DJANGO_SECRET_KEY=django-insecure-b764$$#(&o4o((cvy!z^nsseq5@erq#e^0%5r5a(%c24*f^*sde
      - DJANGO_DEBUG=True
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - DJANGO_EMAIL_BACKEND=django.core.mail.backends.smtp.EmailBackend
      - DJANGO_EMAIL_HOST=smtp.gmail.com
      - DJANGO_EMAIL_PORT=587
      - DJANGO_EMAIL_USE_TLS=True
      - DJANGO_EMAIL_HOST_USER=Ablfxlll@gmail.com  
      - DJANGO_EMAIL_HOST_PASSWORD=curq izbx xclz jhug

  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST_AUTH_METHOD=md5

volumes:
  postgres_data:
