# Generated by Django 5.1.7 on 2025-05-27 10:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productcomment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='product/produc_cover/', verbose_name='Product Image'),
        ),
        migrations.AlterField(
            model_name='productcomment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='Comment author'),
        ),
        migrations.AlterField(
            model_name='productcomment',
            name='body',
            field=models.TextField(verbose_name='Comment Text: '),
        ),
        migrations.AlterField(
            model_name='productcomment',
            name='starts',
            field=models.CharField(choices=[('1', 'very bad'), ('2', 'bad'), ('3', 'normal'), ('4', 'good'), ('5', 'perfect')], max_length=5, verbose_name='What is your rate?'),
        ),
    ]
